const cardHistoryItemMocked = [
  {
    id: "1",
    tag: "Cartão de crédito",
    title: "Compra do mês",
    description: "Compra para casa",
    date: "13/06/2024",
    amount: 637.98,
    transactionType: "Despesa",
  },
  {
    id: "2",
    tag: "Cartão de crédito",
    title: "Supermercado",
    description: "Compra de alimentos",
    date: "05/06/2024",
    amount: 320.75,
    transactionType: "Despesa",
  },
  {
    id: "3",
    tag: "Débito",
    title: "Pagamento de internet",
    description: "Plano mensal",
    date: "01/06/2024",
    amount: 89.99,
    transactionType: "Despesa",
  },
  {
    id: "4",
    tag: "Pix",
    title: "Transferência recebida",
    description: "Pagamento de freelance",
    date: "10/06/2024",
    amount: 1500.0,
    transactionType: "Receita",
  },
  {
    id: "5",
    tag: "Cartão de crédito",
    title: "Assinatura de streaming",
    description: "Serviço mensal",
    date: "07/06/2024",
    amount: 49.9,
    transactionType: "Despesa",
  },
  {
    id: "6",
    tag: "Boleto",
    title: "Conta de luz",
    description: "Energia elétrica",
    date: "15/06/2024",
    amount: 210.45,
    transactionType: "Despesa",
  },
  {
    id: "7",
    tag: "Pix",
    title: "Aluguel recebido",
    description: "Aluguel do apartamento",
    date: "02/06/2024",
    amount: 1200.0,
    transactionType: "Receita",
  },
  {
    id: "8",
    tag: "Débito",
    title: "Farmácia",
    description: "Medicamentos e higiene",
    date: "09/06/2024",
    amount: 78.55,
    transactionType: "Despesa",
  },
  {
    id: "9",
    tag: "Cartão de crédito",
    title: "Gasolina",
    description: "Abastecimento do carro",
    date: "12/06/2024",
    amount: 300.0,
    transactionType: "Despesa",
  },
  {
    id: "10",
    tag: "Boleto",
    title: "Plano de saúde",
    description: "Mensalidade do plano",
    date: "03/06/2024",
    amount: 450.0,
    transactionType: "Despesa",
  },
  {
    id: "11",
    tag: "Pix",
    title: "Venda de produto",
    description: "Venda pelo marketplace",
    date: "14/06/2024",
    amount: 350.0,
    transactionType: "Receita",
  },
  {
    id: "12",
    tag: "Cartão de crédito",
    title: "Restaurante",
    description: "Jantar com amigos",
    date: "08/06/2024",
    amount: 200.0,
    transactionType: "Despesa",
  },
];

export { cardHistoryItemMocked };
